APPNAME = 'grasp-libs-alloy-example'
VERSION = '1.0.0'

srcdir = '.'
blddir = 'build'

def options(opt):
	opt.load("compiler_cxx")

def configure(conf):
	conf.load("compiler_cxx")

def build(bld):
	bld.program(features = "cxx cprogram",
		source = "main.cpp",
		target = "a.out",
        cxxflags = ["-std=c++11"],
        includes = "../../../")
